plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'org.jetbrains.kotlin.jvm'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

neoForge {
    version = neo_version

    runs {
        client { client() }
        server {
            server()
            programArgument '--nogui'
        }
        configureEach {
            logLevel = org.slf4j.event.Level.INFO
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    mavenCentral()
    maven { url "https://thedarkcolour.github.io/KotlinForForge/" }
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.architectury.dev/" }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation files("libs/hexcasting-neoforge-${minecraft_version}-${hexcasting_version}.jar")
    implementation files("libs/hexpose-neoforge-${hexpose_version}.jar")
    implementation files("libs/paucal-${paucal_version}+${minecraft_version}-neoforge.jar")
    localRuntime files("libs/hexcasting-neoforge-${minecraft_version}-${hexcasting_version}.jar")
    localRuntime files("libs/hexpose-neoforge-${hexpose_version}.jar")
    localRuntime files("libs/paucal-${paucal_version}+${minecraft_version}-neoforge.jar")
    localRuntime files("libs/inline-${minecraft_version}-${inline_version}-neoforge-devruntime.jar")
    localRuntime files("libs/caelus-neoforge-${caelus_version}.jar")
    localRuntime files("libs/Patchouli-${minecraft_version}-${patchouli_version}-NEOFORGE.jar")
    localRuntime "dev.architectury:architectury-neoforge:${architectury_version}"
    implementation "thedarkcolour:kotlinforforge-neoforge:${kotlin_for_forge_version}"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

sourceSets.main.kotlin.srcDirs += "src/main/java"
sourceSets.main.java.srcDirs += "src/client/java"
sourceSets.main.kotlin.srcDirs += "src/client/java"

processResources {
    inputs.property "version", project.version
    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 21
}

kotlin {
    jvmToolchain(21)
    compilerOptions {
        freeCompilerArgs.add("-Xjvm-default=all")
    }
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.mod_id}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = project.mod_id
            from components.java
        }
    }
}
